
#define FOOBAR_MAJOR_VERSION (@FOOBAR_MAJOR_VERSION@)
#define FOOBAR_MINOR_VERSION (@FOOBAR_MINOR_VERSION@)
#define FOOBAR_PATCH_VERSION (@FOOBAR_PATCH_VERSION@)
#define FOOBAR_VERSION_STRING "@FOOBAR_VERSION@"
